theme: jekyll-theme-slate

plugins:
- jekyll-sitemap
- jekyll-mentions
- jemoji

jekyll-mentions: https://github.com
author: INDIForJava
title: INDIForJava
description:  >-
  INDIForJava is a set of libraries (written in the Java programming language) to implement clients, drivers and servers
  that follow the INDI distributed control protocol, a protocol designed to operate astronomical instrumentation.
favicons:
  512: '/assets/logo.png'
